#!/usr/bin/env bash
# scripts/delete-bare-skill-dirs.sh — delete the bare-name skill directories and
# rewrite their surviving j-<name> twins' frontmatter (E50_S15).
#
# Purpose
# -------
# Performs E50_S15's own irreversible step: for every skills/<name>/ that still has
# its original, pre-`j-` "bare" directory form alongside its canonical
# skills/j-<name>/ twin, (1) delete the bare directory outright and (2) rewrite the
# twin's SKILL.md frontmatter `name:` field from the transitional `j.j-<name>` form
# to the settled `j.<name>` form (E50_S10's contract). Both steps land together for
# every entry in one script run: renaming the twin first (while the bare directory
# still exists) would leave two directories both claiming `j.<name>`; deleting the
# bare directory first would leave no directory claiming it until the rename
# catches up. Neither intermediate state is ever produced by --apply, because this
# script performs every rewrite before it performs any delete (see step 4 below),
# and only after that first pass completes clean does it touch a filesystem entry.
#
# This script does NOT invoke `git commit`. E50_S15_T04 (the sole task allowed to
# run --apply) is responsible for staging and committing the resulting working-tree
# state as a single atomic commit immediately afterward — mirroring
# scripts/repoint-skill-refs.sh and scripts/apply-j-prefix.sh, neither of which
# commits on the caller's behalf either. Keeping VCS operations at the call site
# (not buried inside this script) keeps the script's own contract to "leave the
# working tree in the correct final state or abort with zero writes" — it does not
# also have to reason about repo-wide staging concerns (what else might already be
# staged, whether a lock file needs to be excluded, etc).
#
# Modes
# -----
#   --dry-run   Report the full computed delete set and, for each entry, the exact
#               frontmatter line change planned. Nothing is written.
#   --apply     Perform the deletion + rename in place. Requires the live count to
#               still match EXPECTED_DELETE_COUNT (see below) or the run aborts
#               with zero filesystem writes.
#
# Exactly one of --dry-run/--apply is required. Either mode always runs the delta
# check and the count cross-check FIRST (see below) before touching or reporting on
# any file.
#
# Usage
# -----
#   scripts/delete-bare-skill-dirs.sh --dry-run
#   scripts/delete-bare-skill-dirs.sh --apply
#
# Delete-set computation — never hardcoded
# ------------------------------------------
# Computed fresh from disk on every invocation: every directory directly under
# skills/ that (a) is not itself "j-"-prefixed, (b) is not one of the three
# permanent exceptions (jenga, jenga-permission-level, index — E50_S06/E50), and
# (c) has a matching skills/j-<name>/ twin on disk. E50_S15_T01 already showed the
# live tree can drift from the story's authoring-time snapshot (6 orphan
# j-<name>-only directories were added after the story was written) — a hardcoded
# name list would silently miss a future drift the exact same way, so the set is
# always recomputed, never literal.
#
# Count cross-check
# ------------------
# EXPECTED_DELETE_COUNT below is the one hardcoded number in this script — not a
# name list, a single integer recorded by E50_S15_T01's live pre-flight recompute
# (2026-09-19: 40). If the live computed delete-set size does not equal this
# number, the script aborts with a non-zero exit and performs zero filesystem
# writes, in either mode. This catches the case where skills/ drifted again
# between T01's recompute and this script actually running --apply.
#
# Bare-vs-twin delta check
# --------------------------
# Before computing the delete set, every bare (non-"j-"-prefixed, non-exception)
# directory under skills/ MUST have a skills/j-<name>/ twin on disk. Any unpaired
# bare directory aborts the run (naming it) before any write — mirrors
# scripts/repoint-skill-refs.sh's identical guard.
#
# Frontmatter rewrite
# ---------------------
# For every delete-set entry <name>, skills/j-<name>/SKILL.md's frontmatter `name:`
# field is rewritten from `j.j-<name>` to `j.<name>`. A twin whose frontmatter does
# not already read exactly `j.j-<name>` is treated as an error (aborts before any
# write) rather than silently skipped or forced — the whole point of this
# cross-check is that any twin already in an unexpected state must be looked at by
# a human, not silently overwritten or silently left behind.
#
# Never touches the generated mirrors
# --------------------------------------
# This script only ever reads/writes under skills/. It has no code path that
# touches .claude/skills/ or .agents/skills/ — those are regenerated by
# /self-sync (E50_S15_T05), never hand-edited here, per CLAUDE.md's standing
# read-only-mirror rule.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# This task's AC requires a clean default-level shellcheck run; SC1091 is an
# info-level "did not follow sourced file" finding that would otherwise fail that
# bar even though the sourced file does exist (see -x). Same fix already applied to
# scripts/apply-j-prefix.sh, scripts/audit-twin-divergence.sh, and
# scripts/build-pages-site.sh.
# shellcheck source=lib/resolve-project-dir.sh disable=SC1091
source "$SCRIPT_DIR/../lib/resolve-project-dir.sh"

PROJECT_DIR="$JENGA_PROJECT_DIR"
SKILLS_DIR="$PROJECT_DIR/skills"

# ---- Single named source: directory exception list (mirrors repoint-skill-refs.sh) ----
DELETE_BARE_SKILL_DIRS_EXCEPTIONS=(jenga jenga-permission-level index)

is_exception() {
  local name="$1" ex
  for ex in "${DELETE_BARE_SKILL_DIRS_EXCEPTIONS[@]}"; do
    if [ "$name" = "$ex" ]; then
      return 0
    fi
  done
  return 1
}

# ---- Single named source: expected delete-set count (E50_S15_T01, 2026-09-19) ----
EXPECTED_DELETE_COUNT=40

usage() {
  cat >&2 <<'EOF'
Usage: delete-bare-skill-dirs.sh (--dry-run|--apply)

  --dry-run   Report the computed delete set and planned frontmatter rewrites.
              Writes nothing.
  --apply     Delete every bare directory in the delete set and rewrite its
              twin's frontmatter name: line, in one pass. Aborts with zero
              writes if the live delete-set count does not match the recorded
              expected count.
EOF
}

MODE=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --dry-run)
      MODE="dry-run"
      shift
      ;;
    --apply)
      MODE="apply"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "delete-bare-skill-dirs.sh: error: unknown argument '$1'" >&2
      usage
      exit 1
      ;;
  esac
done

if [ -z "$MODE" ]; then
  echo "delete-bare-skill-dirs.sh: error: exactly one of --dry-run or --apply is required" >&2
  usage
  exit 1
fi

# ============================================================================
# 1. Live bare-vs-twin delta check — ALWAYS runs first, before any file I/O.
# ============================================================================
BARE_DIRS=()
TWIN_NAMES=()
UNPAIRED=()

if [ -d "$SKILLS_DIR" ]; then
  for d in "$SKILLS_DIR"/*/; do
    [ -d "$d" ] || continue
    name="$(basename "$d")"
    case "$name" in
      j-*)
        TWIN_NAMES+=("${name#j-}")
        continue
        ;;
    esac
    BARE_DIRS+=("$name")
  done
fi

is_twin_name() {
  local target="$1" n
  for n in "${TWIN_NAMES[@]-}"; do
    [ -n "${n:-}" ] || continue
    if [ "$n" = "$target" ]; then
      return 0
    fi
  done
  return 1
}

for name in "${BARE_DIRS[@]-}"; do
  [ -n "${name:-}" ] || continue
  if is_exception "$name"; then
    continue
  fi
  if ! is_twin_name "$name"; then
    UNPAIRED+=("$name")
  fi
done

echo "== delete-bare-skill-dirs.sh: bare-vs-twin delta =="
echo "  bare directories under skills/ (incl. exceptions): ${#BARE_DIRS[@]}"
echo "  twin directories (skills/j-<name>/):                $(printf '%s\n' "${TWIN_NAMES[@]-}" | grep -c . || true)"
if [ "${#UNPAIRED[@]}" -gt 0 ]; then
  echo "  UNPAIRED bare directories (no twin, not on the exception list):"
  for u in "${UNPAIRED[@]}"; do
    echo "    - $u"
  done
  echo "delete-bare-skill-dirs.sh: error: the directory(ies) named above have no skills/j-<name>/ twin and are not on the exception list. Nothing was written. Disposition each one before running this script." >&2
  exit 1
fi
echo "  delta check clean — every bare directory is either excepted or paired with a twin."
echo

# ============================================================================
# 2. Compute the delete set: every bare, non-excepted directory with a twin.
# ============================================================================
DELETE_SET=()
for name in "${BARE_DIRS[@]-}"; do
  [ -n "${name:-}" ] || continue
  if is_exception "$name"; then
    continue
  fi
  DELETE_SET+=("$name")
done

# Sort for deterministic, reviewable output.
if [ "${#DELETE_SET[@]}" -gt 0 ]; then
  SORTED_DELETE_SET=()
  while IFS= read -r n; do
    [ -n "$n" ] || continue
    SORTED_DELETE_SET+=("$n")
  done < <(printf '%s\n' "${DELETE_SET[@]}" | sort)
  DELETE_SET=("${SORTED_DELETE_SET[@]}")
fi

echo "== delete-bare-skill-dirs.sh: computed delete set =="
echo "  count: ${#DELETE_SET[@]} (expected: $EXPECTED_DELETE_COUNT)"
if [ "${#DELETE_SET[@]}" -ne "$EXPECTED_DELETE_COUNT" ]; then
  echo "delete-bare-skill-dirs.sh: error: live delete-set count (${#DELETE_SET[@]}) does not match the recorded expected count ($EXPECTED_DELETE_COUNT, from E50_S15_T01's 2026-09-19 pre-flight recompute). Nothing was written. skills/ has drifted since that recompute -- re-run E50_S15_T01's checks before proceeding." >&2
  exit 1
fi
for n in "${DELETE_SET[@]}"; do
  echo "  - $n"
done
echo "  count check clean."
echo

# ============================================================================
# 3. Pre-validate every twin's current frontmatter name: line before writing
#    anything, in either mode -- an unexpected frontmatter state aborts the
#    whole run rather than being silently skipped or forced.
# ============================================================================
PLANNED=()  # "name|old_line|new_line" per entry, in DELETE_SET order

for name in "${DELETE_SET[@]}"; do
  twin_skill_md="$SKILLS_DIR/j-$name/SKILL.md"
  if [ ! -f "$twin_skill_md" ]; then
    echo "delete-bare-skill-dirs.sh: error: expected twin file not found: $twin_skill_md. Nothing was written." >&2
    exit 1
  fi
  current_line="$(grep -m1 -E '^name:[[:space:]]' "$twin_skill_md" || true)"
  expected_old="name: j.j-${name}"
  new_line="name: j.${name}"
  if [ "$current_line" != "$expected_old" ]; then
    echo "delete-bare-skill-dirs.sh: error: $twin_skill_md's frontmatter name: line reads '$current_line', expected exactly '$expected_old'. Nothing was written. This twin is in an unexpected state -- resolve it manually before re-running." >&2
    exit 1
  fi
  PLANNED+=("${name}|${expected_old}|${new_line}")
done

echo "== delete-bare-skill-dirs.sh: planned frontmatter rewrites (${#PLANNED[@]}) =="
for entry in "${PLANNED[@]}"; do
  IFS='|' read -r name old_line new_line <<< "$entry"
  echo "  skills/j-${name}/SKILL.md: '${old_line}' -> '${new_line}'"
done
echo

if [ "$MODE" = "dry-run" ]; then
  echo "== delete-bare-skill-dirs.sh: dry-run complete — ${#DELETE_SET[@]} director(ies) would be deleted, ${#PLANNED[@]} frontmatter line(s) would be rewritten =="
  echo "  Bare directories that would be deleted:"
  for name in "${DELETE_SET[@]}"; do
    echo "    - skills/${name}/"
  done
  echo "  No files were written. Run with --apply to perform this (E50_S15_T04 only)."
  exit 0
fi

# ============================================================================
# 4. --apply: rewrite every twin's frontmatter FIRST (full pass), then delete
#    every bare directory (full pass). Doing all rewrites before any delete
#    means a mid-run failure during the rewrite pass leaves every bare
#    directory still present (recoverable: nothing deleted yet), and a
#    mid-run failure during the delete pass leaves every twin already
#    correctly renamed (recoverable: re-run recomputes a smaller, still-valid
#    delete set next time, since a twin with no more `j.j-` prefix simply
#    won't re-match the pre-validation above for whichever entries already
#    completed). Neither pass order can leave a "two directories claim
#    j.<name>" state or a "no directory claims it" state uncommitted, because
#    a bare directory is never deleted before its own twin's rename has
#    already succeeded.
# ============================================================================
echo "== delete-bare-skill-dirs.sh: applying frontmatter rewrites =="
for entry in "${PLANNED[@]}"; do
  IFS='|' read -r name old_line new_line <<< "$entry"
  twin_skill_md="$SKILLS_DIR/j-${name}/SKILL.md"
  tmp_file="$(mktemp "${twin_skill_md}.rename.XXXXXX")"
  cp -p "$twin_skill_md" "$tmp_file"
  awk -v old="$old_line" -v new="$new_line" '
    $0 == old && !done { print new; done=1; next }
    { print }
  ' "$twin_skill_md" > "$tmp_file"
  mv "$tmp_file" "$twin_skill_md"
  echo "  rewrote skills/j-${name}/SKILL.md"
done
echo

echo "== delete-bare-skill-dirs.sh: deleting bare directories =="
for name in "${DELETE_SET[@]}"; do
  rm -rf "${SKILLS_DIR:?}/${name:?}"
  echo "  deleted skills/${name}/"
done
echo

echo "== delete-bare-skill-dirs.sh: apply complete — ${#DELETE_SET[@]} director(ies) deleted, ${#PLANNED[@]} frontmatter line(s) rewritten =="
echo "  Working tree now needs a single commit covering both changes (this script does not commit)."
exit 0
